### PR TITLE
Added options to send more fish at a time, updated tooltip

### LINKED ISSUE #62: Add an option to send all fish in your inventory
From VorceShard

Add an option to send all fish in your inventory for spying to save on clicks.

### PR DESCRIPTION
**Pull request by kajendra**
Added more options to send fish, updated the Tooltip with new options.
Tested locally.
Fixes #62 

Left Mouse Button			Sends one fish
Ctrl + Left Mouse Button	Sends 100 fish

Right Mouse Button			Sends half inventory
Ctrl + Right Mouse Button		Sends 50 fish

### Tested Changes
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

### CODE REVIEW

**Comment by AwesomePatrol** [comment]
Looks good. My suggestion is to make it consistent with Factorio's vanilla behavior:
* left click: use 1
* right click: use 5
* shift+left: use all

**Comment by guymaor86** [comment]
I'm with patrol on this one
Maybe also shift right click sends half?

**Comment by kajendra** [comment]
The tooltip looked a bit weird listing all the combinations but I'm more then happy to change it up
I went with 50 and 100 because factorio standards are to send half the stack size and stack size is 100.

I agree with the suggestions, going to post it to discord as well to verify and implement.

**Comment by kajendra** [comment]
Updated as per community suggestion to:
left click: use 1
right click: use 5
shift+left: use all
shift+right: use half

Fixed the tooltip and update message to include minute(s) and seconds of spy time left.

**Review by guymaor86 — APPROVED** [review]

**Pull request merged**
