### PR TITLE
Chat cmd updates

### PR DESCRIPTION
**Pull request by kajendra**
### Brief description of the changes:
- Added profanity warning to chatbot.
- Cleaned chat command, removed unused `-n` and `-s` commands
- Removed GPS coordinates and player Tag from being sent to discord
- Added end game reminders about Captains mode

Tested the changes locally and with other people.

### Tested Changes
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

### CODE REVIEW

**Comment by guymaor86** [comment]
@kajendra you have some conflicts

**Comment by kajendra** [comment]
Yeah #82 was meant to be applied after my PR
Need to ensure that #82 stays in effect

**Comment by guymaor86** [comment]
i merged from oldest to newest i think, so 82 was applied first
anyways should be an easy resolve

**Comment by kajendra** [comment]
Yep, I saw the conflict was going to happen before I started my branch after seeing your fix.
And that makes sense to go chronologically.
Thought it would resolve itself at time to merge, but it's fine now :)

**Review by guymaor86 — APPROVED** [review]

**Pull request merged**
